#加密
jasypt:
  encryptor:
    password: 123456!@#

info:
  username: ENC(Wp3nEDrrvLzK+W+sidb5Hw==)
  password: ENC(sRuHGEFRtB5Knfs6Qa/wOA==)


food:
  meat: 烤肉
  rice: 拌饭

#流式语法   使用冒号/缩进/流式（key: {key:value,key:value}）
vegetables: {potato: 土豆,eggplant: 茄子}

spring:
  profiles:
    active: prod

---
#开发环境
spring:
  profiles: dev

server:
  port: 8090

---
#生产环境
spring:
  profiles: prod

server:
  port: 8090